export function cleanEmDashes(text: string): string {
  if (!text) return "";
  return text
    .replace(/[—–]/g, "-")
    .replace(/ - - /g, " - ")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n");
}

export function cleanTranscript(text: string): string {
  if (!text) return "";
  const watermarkRegex = /---\s*Generated by https:\/\/youtube-transcript\.ai[^\n]*/gi;
  return text.replace(watermarkRegex, "").trim();
}

function stripCodeWrappers(text: string): string {
  if (!text) return "";
  let cleanText = text.trim();



  const mdBlockRegex = /^```[a-zA-Z]*\n([\s\S]*?)```$/i;
  const mdMatch = cleanText.match(mdBlockRegex);
  if (mdMatch && mdMatch[1]) {
    cleanText = mdMatch[1].trim();
  }


  if (cleanText.startsWith("```") && cleanText.endsWith("```")) {
      cleanText = cleanText.replace(/^```[a-zA-Z]*\n?/, "").replace(/```$/, "").trim();
  }



  const pyWrapperRegex = /^def\s+[a-zA-Z0-9_]+\s*\([^)]*\)\s*(?:->\s*[a-zA-Z]+\s*)?:\s*return\s*["']{3}([\s\S]*?)["']{3}\s*$/i;
  const pyMatch = cleanText.match(pyWrapperRegex);
  if (pyMatch && pyMatch[1]) {
    cleanText = pyMatch[1].trim();
  }


  if (cleanText.includes('def ') && (cleanText.includes('return """') || cleanText.includes("return '''"))) {
      const aggressivePyRegex = /return\s*["']{3}\s*([\s\S]*?)\s*["']{3}/;
      const aggMatch = cleanText.match(aggressivePyRegex);
      if (aggMatch && aggMatch[1]) {
         cleanText = aggMatch[1].trim();
      }
  }

  return cleanText;
}

export async function generateContent(prompt: string, systemInstruction: string): Promise<string> {
  const res = await fetch("/api/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, systemInstruction })
  });

  if (!res.ok) {
    const errorData = await res.json();
    throw new Error(errorData.error || "Gagal membuat konten");
  }

  const data = await res.json();
  const rawText = data.text || "";
  const cleanedText = stripCodeWrappers(rawText);
  return cleanEmDashes(cleanedText);
}

export function splitIntoSentences(text: string): string[] {


  const regex = /[^.!?]+[.!?]+(?=\s|$)/g;
  let matches = text.match(regex);
  
  if (!matches) {

    return [text.trim()].filter(s => s.length > 0);
  }

  return matches.map(s => s.trim()).filter(s => s.length > 0);
}

export function parseBatchPrompts(resultText: string, expectedCount: number): string[] {
  const prompts: string[] = new Array(expectedCount).fill("");


  try {
    const jsonMatch = resultText.match(/\{[\s\S]*\}|\[[\s\S]*\]/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      let items: any[] = [];
      if (Array.isArray(parsed)) {
        items = parsed;
      } else if (parsed && typeof parsed === "object") {
        items = parsed.prompts || parsed.data || parsed.items || Object.values(parsed);
      }

      if (Array.isArray(items)) {
        items.forEach((item, index) => {
          let text = "";
          let itemNum = index + 1;
          if (typeof item === "string") {
            text = item;
          } else if (item && typeof item === "object") {
            text = item.prompt || item.englishPrompt || item.text || item.description || item.visual || "";
            if (item.number) itemNum = Number(item.number);
            else if (item.index) itemNum = Number(item.index);
          }

          const targetIdx = itemNum - 1;
          if (targetIdx >= 0 && targetIdx < expectedCount && text.trim()) {
            prompts[targetIdx] = text.trim();
          }
        });

        if (prompts.some(p => p && p.trim().length > 0)) {
          return prompts;
        }
      }
    }
  } catch (e) {

  }


  const lines = resultText.split("\n").map(l => l.trim()).filter(Boolean);

  lines.forEach(line => {
    const numMatch = line.match(/^(?:\*\*|\*|\[)?(?:Sentence\s*)?(\d+)(?:[\.\)\:\-]|\])?\s*(?:\*\*)?\s*(.*)$/i);
    if (numMatch) {
      const num = parseInt(numMatch[1], 10);
      let content = numMatch[2].trim();
      content = content.replace(/^(?:Visual Prompt|Visual|Prompt|English Prompt)\s*\:\s*/i, "").trim();
      content = content.replace(/^["']|["']$/g, "").trim();

      const targetIdx = num - 1;
      if (targetIdx >= 0 && targetIdx < expectedCount && content && !prompts[targetIdx]) {
        prompts[targetIdx] = content;
      }
    }
  });


  let linePointer = 0;
  for (let i = 0; i < expectedCount; i++) {
    if (!prompts[i]) {
      while (linePointer < lines.length) {
        let candidate = lines[linePointer].replace(/^(?:\*\*|\*|\[)?(?:Sentence\s*)?(\d+)(?:[\.\)\:\-]|\])?\s*(?:\*\*)?\s*/i, "").trim();
        candidate = candidate.replace(/^(?:Visual Prompt|Visual|Prompt|English Prompt)\s*\:\s*/i, "").trim();
        candidate = candidate.replace(/^["']|["']$/g, "").trim();
        linePointer++;

        if (candidate.length > 10 && 
            !candidate.toLowerCase().startsWith("here are") && 
            !candidate.toLowerCase().startsWith("sure") &&
            !candidate.toLowerCase().startsWith("translation") &&
            !candidate.toLowerCase().startsWith("json")) {
          prompts[i] = candidate;
          break;
        }
      }
    }
  }

  return prompts;
}
